Social-Network-master/bffbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view, signup_view, login_view, handlesignup, handlelogin, handlelogout
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('login_view/', login_view, name='login-view'),
    path('signup', views.handlesignup, name="handlesignup"),
    path('login', views.handlelogin, name="handlelogin"),
    path('logout', views.handlelogout, name="handlelogout"),
    path('signup_view/', signup_view, name='signup-view'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Social-Network-master/posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

Social-Network-master/profiles/urls.py
from django.urls import path
from .views import ( 
    my_profile_view, 
    invites_received_view, 
    profiles_list_view, 
    invite_profiles_list_view, 
    ProfileDetailView,
    ProfileListView,
    send_invatation,
    remove_from_friends,
    accept_invatation,
    reject_invatation,
)

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('send-invite/', send_invatation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/acctept/', accept_invatation, name='accept-invite'),
    path('my-invites/reject/', reject_invatation, name='reject-invite'),
]

Social-Network-master/templates/main/home.html
{% extends 'base2.html' %}

{% block title %}
home
{% endblock title %}

{% block content %}
<!--login and signup box-->
{% if user.is_authenticated %}
{% else %}
<br xmlns="http://www.w3.org/1999/html">
<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column">
      <div class="ui form">
        <div class="field">
          <form action="/login" method="post">
            {% csrf_token %}
                <label for="loginusername">Username</label>
                <div class="ui left icon input">
                  <input type="text" id="loginusername" name="loginusername" placeholder="Username">
                  <i class="user icon"></i>
                </div>
              </div>
              <div class="field">
                <label for="loginpassword">Password</label>
                <div class="ui left icon input">
                  <input type="loginpassword" name="loginpassword" id="loginpassword">
                  <i class="lock icon"></i>
                </div>
              </div>
              <button type="submit" class="ui blue submit button">Login</button>
          </form>
      </div>
    </div>
    <div class="middle aligned column">
      <div class="ui big button">
        <form action="signup_view/" method="post">
          {% csrf_token %}
        <button type="submit" href="signup_view/" class="signup icon ui blue submit massive button">Create a New Account</button>
      </div></form>
    </div>
  </div>
  <div class="ui vertical divider">
    Or
  </div>
</div>
{% endif %}
<!--code ends here-->

<hr>
<h1 style="text-align:center;" >Welcome to Social Website made on django framework by Python</h1>
<h1 style="text-align:center;"><strong> - Made by Akash Poddar</strong></h1>
<hr>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" style="width: inherit;" >
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://images.unsplash.com/photo-1461749280684-dccba630e2f6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://images.unsplash.com/photo-1504639725590-34d0984388bd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://vistapointe.net/images/hacker-1.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<!--caraousel code ends here-->
<br>
<h2>Welcome to my website, My website has such fuctionalities: </h2>
<br>
<div class="ui cards">
  <div class="card">
    <div class="content">
      <div class="header">Login and Signup</div>
      <div class="description">
        <p>You can Login and Signup !</p>
          <p>You can create a new account very easy..!</p>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="content">
      <div class="header">Meet everyone !</div>
      <div class="description">
        <p>After creating account, you can easily login with your credentials.</p>
        <p>In the "All Profiles" on navbar, you can see all the profiles or users registered on this website.</p>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="content">
      <div class="header">Communicate with friends !</div>
      <div class="description">
          <p>Add any Friends, by sending Friend Request.</p>
          <p>Be Friend of any Friend, by accepting friends request.</p>
          <p>Feeling not comfortable ? You can remove any friend if you don't want to continue friendship.</p>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="content">
      <div class="header">Post Anything !</div>
      <div class="description">
          <p>You can post anything, at anytime and anywhere.</p>
          <p>You can like any post.</p>
          <p>You can comment on any post.</p>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="content">
      <div class="header">Security Measures !</div>
      <div class="description">
          <p>You can easily log in into my website, My website does not store your password, it uses hashing system.</p>
          <p>OnetoOneField, means you can be the only one user of your kind !</p>
          <p>From login to logout everything is secured.</p>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="content">
      <div class="header">Open Source !</div>
      <div class="description">
          <p>You can download source code in github here:
            <a href="https://github.com/akashpoddarr/akash_website.git">https://github.com/akashpoddarr/akash_website.git</a>
          </p>
      </div>
    </div>
  </div>
</div>



<br>
<br>
<br>
<br>
<br>
<hr>
<!--footer code starts here-->
<div class="container" style="
    margin-inline-start: 288px;
">
<!-- Footer -->
<footer class="page-footer font-small cyan darken-3">

  <!-- Footer Elements -->
  <div class="container">

    <!-- Grid row-->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-12 py-5">
        <div class="mb-5 flex-center">

          <!-- Facebook -->
          <a class="fb-ic">
            <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic">
            <i class="fab fa-google-plus-g fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic">
            <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x" href="https://www.instagram.com/iam_aakashhh/"> </i>
          </a>
          <!--Pinterest-->
          <a class="pin-ic">
            <i class="fab fa-pinterest fa-lg white-text fa-2x"> </i>
          </a>
        </div>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->

  </div>
  <!-- Footer Elements -->
</footer>
<!-- Footer -->
</div>
{% endblock content %}

{% block scripts %}
<script>
$(document).ready(function(){
    console.log('working')
})
</script>
{% endblock scripts %}

Social-Network-master/templates/main/login_page.html
{% extends 'base2.html' %}

{% block title %}
login
{% endblock title %}

{% block content %}
<form action="/login" method="post">
  {% csrf_token %}
<div class="ui placeholder segment" style="width:550px; margin-top:200px; margin-left:200px; " >
    <div class="column">
      <div class="ui massive form">
        <div class="field">
          <label for="loginusername">Username</label>
          <div class="ui left icon input">
            <input type="text" id="loginusername" name="loginusername" placeholder="Username">
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <label for="loginpassword">Password</label>
          <div class="ui left icon input">
            <input type="password" id="loginpassword" name="loginpassword" >
            <i class="lock icon"></i>
          </div>
        </div>
        <button type="submit" class="ui blue submit massive button" style="margin-left: 174px;">Login</div>

      </div>
    </div>
  </div>
</form>










{% endblock content %}

{% block scripts %}
<script>
$(document).ready(function(){
    console.log('working')
})
</script>
{% endblock scripts %}

Social-Network-master/templates/main/navbar.html
{% url 'home-view' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:my-invites-view' as path_to_my_invites %}
{% url 'profiles:invite-profiles-view' as path_to_invites %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}

<div class="ui inverted menu nav mb-7">
  <div class="ui container">
    <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
        <h3>Akash's Website</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
        Feed
    </a>
    {% endif %}
        {% if request.user.is_authenticated %}
      <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
          All Profiles
      </a>
      <a href="{{path_to_invites}}" class="{% if request.path == path_to_invites %}active{% endif %} item">
          Send Invites
      </a>
      <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                        Receive All Requests
      </a>
    </div>
    <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                 Welcome &nbsp;{{ request.user }}
    </a>
    <a href="/logout" class="ui item">
        Logout&nbsp;<i class="power off big alternate icon"></i>
    </a>
    {% else %}
    <a href="login_view/" class="ui item">
        Login <i class="sign in big alternate icon"></i>
    </a>
    <a href="signup_view/" class="ui item">
        Signup
    </a>
        {% endif %}
    </div>
  </div>

Social-Network-master/templates/main/nothing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>



<div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui floating dropdown icon button teal"> Friends
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                        All Profiles
                    </a>
                    <a href="{{path_to_invites}}" class="{% if request.path == path_to_invites %}active{% endif %} item">
                        Send Invites
                    </a>
                    <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                        Received Invites
                    </a>
                </div>
             </div>
        </div>
             <div class="item">
              <form action="" method="GET">
                <div class="ui action left icon input">
                <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                <i class="search icon"></i>
                <button type='submit' class="ui button">Search</button>
                </div>
            </form>
            </div>

            <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                 {{ request.user }}
            </a>

            <a href="" class="ui item">
                Logout
            </a>
        {% else %}
        <a href="login_view/" class="ui item">
                Login
            </a>
         <a href="signup_view/" class="ui item">
                Signup
            </a>
        {% endif %}
    </div>
  </div>


</body>
</html>